version: '3.8'

services:
  backend:
    container_name: development
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    tty: true
  mongo:
    image: mongo:7.0.5-jammy
    ports:
      - 27017:27017
    