version: '3.8'

services:
  development:
    container_name: development
    build:
      dockerfile: ./Dockerfile
      args:
        version: ${NODE_VERSION}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    tty: true
  mongo:
    image: "mongo:${MONGO_VERSION}"
